### ISSUE TITLE
Create plugin base for AesirX Analytics

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/joomla-analytics-plugin#1]
We need a Joomla plugin to be able to use AesirX Analytics to capture pages visits through the Joomla installation and connect to a 1st party server to report them.

Essentially it needs to use https://github.com/aesirxio/analytics and wrap it up in a Joomla plugin, so it's an easy-to-install solution.

The plugin needs to be configurable so that it can set the license details, 1st party server etc to be configured from the plugin configuration.

**Comment by shandak** [comment]
@jatitoam only for Joomla 4?

**Comment by jatitoam** [comment]
yes

**Comment by thaoredweb** [comment]
It works for joomla4.2.9 @jatitoam 
![image](https://user-images.githubusercontent.com/30283123/226530847-1f580801-b55f-47fa-8b0d-9861e1aac23a.png)
